language: node_js
node_js: node

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build
  - npm run generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: \$GITHUB_ACCESS_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
